rvm:
  - "2.0.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive texlive-xetex texlive-latex-extra
  - sudo apt-get install -qq inkscape
  - sudo python -c "import sys; py3 = sys.version_info[0] > 2; u = __import__('urllib.request' if py3 else 'urllib', fromlist=1); exec(u.urlopen('http://status.calibre-ebook.com/linux_installer').read()); main()"
  - export PATH=$PATH:`echo ~`
  - curl -O -L https://github.com/IDPF/epubcheck/releases/download/v3.0/epubcheck-3.0.zip && unzip epubcheck-3.0.zip -d ~
  - curl -o ~/kindlegen http://softcover-binaries.s3.amazonaws.com/kindlegen && chmod +x ~/kindlegen
