version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: install deps
          command: |-
              gem install -v 2.1.4 bundler
              sudo apt-get update -qq
              sudo apt-get install -qy cabextract
              wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb
              sudo dpkg -i ttf-mscorefonts-installer_3.6_all.deb
              sudo apt-get install -qy --no-install-recommends texlive-full texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra fonts-gfs-bodoni-classic
              sudo apt-get install -qq inkscape ghostscript
              sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh
              echo 'export PATH=$PATH:`echo ~`' >> $BASH_ENV
              curl -O -L https://github.com/IDPF/epubcheck/releases/download/v4.0.2/epubcheck-4.0.2.zip && unzip epubcheck-4.0.2.zip -d ~
              curl -o ~/kindlegen http://softcover-binaries.s3.amazonaws.com/kindlegen && chmod +x ~/kindlegen
              wget https://softcover-static.s3.amazonaws.com/Bodoni%2072%20Smallcaps%20Book.ttf && sudo cp Bodoni%2072%20Smallcaps%20Book.ttf /usr/share/fonts/truetype/bodoni-classic
              sudo fc-cache -fsv
          # gem i softcover && softcover check # NOTE: enable to troubleshoot tex, gs, calibre, epubcheck, kindlegen issus
      - ruby/bundle-install
      - run:
          name: specs
          command: bundle exec rspec -f d
